### ISSUE TITLE
有关属性预测器训练

### ISSUE THREAD

**Issue by Winnie202** [yumingj/Talk-to-Edit#10]
在[https://github.com/yumingj/Talk-to-Edit/issues/5](url)中看到有关自定义数据集的问题，但是这个里面都没有提及到输入数据的结构，我目前想在自定义数据集上训练属性预测器，但是训练数据的具体数据结构是什么样子的，有没有一个样式可供参考一下吗？非常感谢。

**Comment by yumingj** [comment]
属性预测器的训练数据就是(image, attribute labels)这样的pair。跟训分类网络的思路是一样的
