### ISSUE TITLE
预训练好的身份识别模型

### ISSUE THREAD

**Issue by dengshuhai-cmd** [yumingj/Talk-to-Edit#11]
能提供一下预训练的arcface_resnet18_110.pth模型的链接吗，我在Arcface: Additive angular margin loss for deep
face recognition.的github上好像没有找到训练好的模型。

**Comment by yumingj** [comment]
在我们提供的预训练模型里就有：https://drive.google.com/drive/folders/1W9dvjz8bUolEIG524o8ZvM62uEWKJ5do

**Comment by dengshuhai-cmd** [comment]
你可能理解错我的意思了，我不是要你训练好的（寻找方向场的模型），我是想要你们在训练过程中loss中计算Lid_loss的身份识别模型（arcface），因为我在arcface的网站上没有找到预训练的arcface模型。因为我想要要使用你们的方法其他数据集上实验（如pggan1024等等）。

**Comment by yumingj** [comment]
在这个链接里有包括arcface的预训练模型了。
