### ISSUE TITLE
Not working on real images

### ISSUE THREAD

**Issue by royaloctave** [yumingj/Talk-to-Edit#3]
Thank you for the great work. I'm currently trying to use "editting_wo_dialog" on real images but the algorithm doesn't produce the results! I use exactly the same setting and models you provided. I just only change the input image. I get the following message at the end:

```
2021-10-25 12:42:50,212.212 - INFO: Sample 000 is already at the target class, skip.
2021-10-25 12:42:50,212.212 - INFO: This attribute is already at the degree that you want. Let's try a different attribute degree or another attribute.
```

sometimes it also gives something like this:
```
total: 0.2573; perceptual: 0.2314; mse: 0.0259; lr: 0.0000: 100%|█| 600/600 [00:59<00:00, 10
2021-10-25 12:40:12,199.199 - INFO: Sorry, we are unable to edit this attribute. Perhaps we can try something else.

```

Here I upload the input and output for your reference.
![3](https://user-images.githubusercontent.com/92549532/138683852-420abd39-5242-455b-85af-0ab53293bb52.png)

![cropped](https://user-images.githubusercontent.com/92549532/138683339-88754abc-a7fe-4f61-8ae2-fbe26bef703b.png)
![start_image](https://user-images.githubusercontent.com/92549532/138683348-35f1a53e-6825-47cc-85b1-ebcf07362c51.png)

How can I run the code properly on real images?

**Comment by zhanghm1995** [comment]
@royaloctave, 
Hi, I also got the similar results and messages like yours when I test the real image. I want to know whether you have get the expected results when changing resolution to 128?

And what the config file you used? Have you modified anything?
