### ISSUE TITLE
How to encode the text information into the semantic field

### ISSUE THREAD

**Issue by lsm123123** [yumingj/Talk-to-Edit#4]
I revise the code and i am wondering whether to encode the text-guided feature into the semantic field so that it can be modified to a cross-modal semantic field conditioned on the text.

**Comment by yumingj** [comment]
Hi, thanks for your interest in our work!

In our implementation, we do not encode the text information into the semantic field directly. However, I think it is possible to encode the text information into the semantic field. Maybe you can use LSTM layers (or some other text feature extractor) to extract the text features first. And then concat the text-guided feature with the input latent code, and use the concated feature as the input.

**Comment by lsm123123** [comment]
> Hi, thanks for your interest in our work!
> 
> In our implementation, we do not encode the text information into the semantic field directly. However, I think it is possible to encode the text information into the semantic field. Maybe you can use LSTM layers (or some other text feature extractor) to extract the text features first. And then concat the text-guided feature with the input latent code, and use the concated feature as the input.

Thank you for your reply! I will build a baseline based on this nice work and try some novel ideas.
Furthermore, i want to contact you with WeChat for further communications.
My research interest is also text-driven image generation and editing.

**Comment by lsm123123** [comment]
> Hi, thanks for your interest in our work!
> 
> In our implementation, we do not encode the text information into the semantic field directly. However, I think it is possible to encode the text information into the semantic field. Maybe you can use LSTM layers (or some other text feature extractor) to extract the text features first. And then concat the text-guided feature with the input latent code, and use the concated feature as the input.

Is it convenient for you to leave your wechat for further communication?

**Comment by yumingj** [comment]
Hi, you can leave your wechat id here~

**Comment by lsm123123** [comment]
> Hi, you can leave your wechat id here~

OK, my wechat id is xhjx123123. I'd like to exchange academic content with you!!
