### ISSUE TITLE
“训练数据集”

### ISSUE THREAD

**Issue by zhangshen12356** [yumingj/Talk-to-Edit#6]
你好，我想自己训练自己的数据集（分辨率为256x256)，但是我看你这项工作中128x128的图片好像都没有额头，请问你们是在一幅大图中利用人脸检测器检测出人脸然后resize到128的吗？

**Comment by yumingj** [comment]
嗯嗯 是的。我们使用人脸检测器检测出人脸之后resize到128的。resize和crop人脸的方式要与训练stylegan的方式保持一致。

**Comment by zhangshen12356** [comment]
> 嗯嗯 是的。我们使用人脸检测器检测出人脸之后resize到128的。resize和crop人脸的方式要与训练stylegan的方式保持一致。

好的，谢谢
