### ISSUE TITLE
An error occurs when upfirdn2d() is called

### ISSUE THREAD

**Issue by lishanlu136** [yumingj/Talk-to-Edit#8]
error msg: upfirdn2d(): incompatible function arguments. The following argument types are supported:
    1. (arg0: at::Tensor, arg1: at::Tensor, arg2: int, arg3: int, arg4: int, arg5: int, arg6: int, arg7: int, arg8: int, arg9: int) -> at::Tensor

**Comment by yumingj** [comment]
The reason could be the wrong environment for StyleGAN2-PyTorch. You may need to check your CUDA version and GCC version.
